### PR TITLE
Add extra jvm args after the jar is specified.

### PR DESCRIPTION
**Pull request by mhemesath**

### CODE REVIEW

**Comment by dhoer** [comment]
Can you please explain why this is needed?  Are you passing args to selenium jar?  I probably should have called it jvm_options instead of jvm_args based on this:
http://docs.oracle.com/javase/8/docs/technotes/tools/windows/java.html

**Comment by mhemesath** [comment]
When I add jvm_arguments to the LWRP the service won't start. When I flip them in the init file, it then works.

**Comment by dhoer** [comment]
What platform and jdk are you using?

**Comment by mhemesath** [comment]
Java 7 on redhat 6.6

**Comment by dhoer** [comment]
open or oracle java?

**Comment by mhemesath** [comment]
Sorry, oracle Java

**Comment by dhoer** [comment]
Can you please provide the args you are passing in?

**Comment by dhoer** [comment]
I added centos 6.6 to kitchen and  -Xms1024m to selenium_test node recipe and can't get it to fail.

**Comment by mhemesath** [comment]
Here is what my recipe has

``` rb
selenium_hub 'selenium_hub' do
  jvm_args "-newSessionWaitTimeout 25000 -timeout 60 -browserTimeout 60"
  action :install
end
```

**Comment by dhoer** [comment]
Those arguments are managed by the selenium_hub lwrp:

```
selenium_hub 'selenium_hub' do
  newSessionWaitTimeout 2500
  timeout 60
  browserTimeout 60
end
```

**Comment by dhoer** [comment]
I have updated the readme attributes sections to mention that this is only a partial list.  I also removed jvm_args from the example to avoid confusion.  Does this make it clearer on how to use selenium?

**Comment by mhemesath** [comment]
Yup, thanks.

**Pull request closed without merging**
